GET, POST, PATCH and DELETE request handlers for user profile REST API
Kenttrann2302/StudyHub-Backend pull request #14
Opened 2023-04-20 15:03 UTC by Kenttrann2302

Finishing GET, POST, PATCH and DELETE methods for the user profile REST API, finish the manual client tests for them as well (inside the Test_RESTAPI folder), still need to write automatic tests to test if the server responses correctly to all kinds of requests.

2023-04-20 15:45 UTC, j-ngo828 requested changes
The overall logic works, I requested some changes related to serialization of user information in the POST and PATCH request handler.

Most of the changes I suggested are code style related, let's follow convention as much as possible. I also suggested change to error message to reduce redundancy.

I want to change the model name, but I can help you with that later. For the variables renaming, please use a sensible tool like VSCode find all references or rename symbol instead of trying to read thru thousands of lines of code in the entire repo to rename it.

For the Marshmallow suggestion, I want to use that also, makes validation much much better. But that probably should be in a separate issue.

If you have any questions/concerns/doubt, reply to this comment here.

2023-04-20 15:45 UTC, j-ngo828 commented on user_profile.py
> +userInformation_resource_fields = {
nit: Python variable convention is snake case

```suggestion
user_information_resource_fields = {
```

Be sure to update the places where this is used to

2023-04-20 15:45 UTC, j-ngo828 commented on user_profile.py
> +            if request.method == 'GET':
Do you need to check `request.method` here? Doesn't the `Resource` class already handles this.

So if the method name is `get`, it only gets executed when request is `get`, same thing for `post`, `delete`, and `patch`

2023-04-20 15:45 UTC, j-ngo828 commented on user_profile.py
> +    @marshal_with(userInformation_resource_fields)  # serialize the instance object
nice! good use of external library.

I'm contemplating a different solution which is Marshmallow that offers not only serialization, deserialization but also validation.

`marshal` doesn't seem to offer validation. I will give it more thought after doing some more investigation

2023-04-20 15:45 UTC, j-ngo828 commented on user_profile.py
> +                                }
Hmm for security reason, let's not expose the `user_id` here. We only need to tell the client user existed.

```suggestion
                                    'message' : f"User already exist"
                                }
```

No need to mention database.

2023-04-20 15:45 UTC, j-ngo828 commented on user_profile.py
> +                            response_data = {"message" : f"User's information has been added successfully!"}
This is a successful POST request, we do not need message here, a POST request with status 201 indicates the resource (in this case user information) is created successfully.

Let's serializes the user information data (but do not include the `id` of the user information) , and include it in the response. For context: frontend will use the data created to display user information

2023-04-20 15:45 UTC, j-ngo828 commented on user_profile.py
>                                  "message": f"Cannot add the profile for user with user_id: {user_id} into the database",
See my message above about `user_id`

2023-04-20 15:45 UTC, j-ngo828 commented on user_profile.py
> +            "profile_image",
So this field is snake case, but `postalCode`, `firstAddress`, and other fields are camel case.

Let's use snake case here to follow Python convention. The client can change the field name easily to send the correct data to the server.

`formData` is also in camelcase, let's change that to snake case: `form_data`

2023-04-20 15:45 UTC, j-ngo828 commented on user_profile.py
> +    def __formData_addArguments(self, formData) -> None:
Again, snake case

```suggestion
    def __form_data_add_arguments(self, formData) -> None:
```

2023-04-20 15:45 UTC, j-ngo828 commented on user_profile.py
>  class UserInformationResource(Resource):
If you're wondering, this class name follows the pascal case convention correctly.

So in Python, class name must be pascal case: `LikeThisExampleClass`, and all variables should be snake case:

- `this_variable_for_example`
- `_private_variable`
- `__private_method`

2023-04-20 15:45 UTC, j-ngo828 commented on database/users_models.py
>  class UserInformation(db.Model):
This model name will possibly need to change since some error message say user profile, and some say user information.

2023-04-20 15:45 UTC, j-ngo828 commented on database/users_models.py
>    __tablename__ = 'user_information'
Please format this with `black` so that this is double quoted

2023-04-20 15:50 UTC, j-ngo828 commented
Also one thing to call out, don't name the models directory database, name it `models`.

Similarly for tests, ideally we create a `tests` directory, then we create sub-directory for feature, so `tests/user-profile/` for example. Then within that subdirectory we have test file, as well as any other file related to testing user profile. Then we have file for integration testing like `tests/test_login.py` that tests the entire flow of registration -> verify -> login. Then we also have directories for testing utils and constants like `tests/utils/` and `tests/constants/`

Similar for API code, it should be in `controllers/` directory, then `controllers/user-profile/` for example. You get the idea. Why? Convention, convention, convention. There's a reason why there's convention and best practices like this to help with organizing code and readability of the code base in general.

Do not make the change in this issue. This issue only handles CRUD operation of user profile, not refactoring and organizing code and utilize a different library for serialization and validaition.

2023-04-21 17:22 UTC, j-ngo828 commented on database/users_models.py
>    __tablename__ = 'user_information'
The black Python formatter https://black.readthedocs.io/en/stable/getting_started.html

Activate the virtual environment, then do `pip install black`. Then run `black path-to-file/users_model.py` to format this file. You can also setup the formatting in PyCharm, just google how.

2023-04-21 17:23 UTC, j-ngo828 commented
Need the commit on your local branch to be pushed here to this PR, it'd be easier for me to work on your existing work instead of redoing your step in my local branch

2023-04-22 13:11 UTC, j-ngo828 approved these changes
Leaving the `print` statement as is for now it's fine. We can clean it up later.

LGTM!

Please squash and merge the commits. The commit message should be something along the line of "Add CRUD operations for UserProfile"

2023-04-22 15:43 UTC, Kenttrann2302 commented
My first PR has been merged!!!!

2023-04-22 15:45 UTC, merged

2023-04-22 15:46 UTC, j-ngo828 commented
Don't restore the branch. We only restore it when needed